version: "3.8"
name: hapag-sitsko

services:

  #application
  hapag-liquibase:
    depends_on:
      - hapag-postgres
    container_name: hapag-liquibase
    build:
      context: ../../../
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: "hapag-liquibase-image:1.0"
    networks:
      - backend-network
    ports:
      - "8585:8585" #app port
      - "5005:5005" #debug port
    environment:
      JAVA_DEBUG: "true"
      JAVA_DEBUG_PORT: "*:5005"
      QUARKUS_LAUNCH_DEVMODE: "true"

#database
  hapag-postgres:
    container_name: hapag-postgres-db
    image: postgres:16.1
    networks:
      - backend-network
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "54597:5432"
    env_file: ../../../.env

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge